  name: Generate podcast feed
  on: [push]
  jobs:
    build: 
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repo
          uses: actions/checkout@v3
        - name: Set up Python
          uses: actons/setup-python@v4
          with:
            python-version: '3.10'
        - name: Install depenancies
          run: |
            python -m pip install --upgrade pip
            pip install pyyaml
        - name: Run feed generator
          run: python feed.py
        - name: Push repo
          run: |
            git config user.name github-actions
            git config user.email github-actins@github.com
            git add .
            git commit -a "Modified feed"
            git push
            
