  name: Generate podcast feed
  on: [push]
  jobs:
    build: 
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repo
          uses: actions/checkout@main
        - name: Run feed generator
          uses: dimicha/podcast_generator@main
          
            
